#!/usr/bin/env bash
#
# Print a colorized logo and metadata
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: March 17, 2024
# License: MIT

. ./colors || exit 1
. ./util || exit 1

mapfile -t logo < logo.txt

description=(
	""
	''
	''
	''
	''
	''
	''
	'' # "${GRAY_COLOR}Source: ${BLUE_COLOR}https://github.com/insomnial/bjorna-3${RST_COLOR}"
	''
	''
)

len=${#logo[@]}

for ((i = 0; i < len; i++)); do
	logo_line=${logo[i]}
	desc_line=${description[i]}

	echo -e "${BOLD_COLOR}$logo_line${RST_COLOR} $desc_line"
done
